const bottom_bracket= require('./bottom_bracket')
const brakeset= require('./brakeset')
const brand= require('./brand')
const cassette= require('./cassette')
const chain= require('./chain')
const chainring= require('./chainring')
const crank_arm= require('./crank_arm')
const crankset= require('./crankset')
const fork= require('./fork')
const front_travel= front_travel('./front_travel')
const grips= require('./grips')
const handlebar= require('./handlebar')
const headset= require('./headset')
const hubs= require('./hubs')
const iscg_tabs= require('./iscg_tabs')
const rear_travel= require('./rear_travel')
const rotor= require('./rotor')
const saddle= require('./saddle')
const seatpost= require('./seatpost')
const shifter= require('./shifter')
const stem= require('./stem')
const tire= require('./tire')
const warranty= require('./warranty')
const wheelset= require('./wheelset')

module.exports= { bottom_bracket, brakeset, brand, cassette,chain, chainring, crank_arm, crankset,fork, front_travel, grips, handlebar, headset, hubs, iscg_tabs, rear_travel, rotor, saddle, seatpost,
shifter, stem, tire, warranty, wheelset }